/*
 * This file is autogenerated, see util/job-gen.py and dat/jobs/ for more info.
 */
#pragma once

static job_group job_groups[] =
{

    {
        "Warrior",
        coord_def(0, 0),
        15,
        { JOB_FIGHTER, JOB_GLADIATOR, JOB_MONK, JOB_HUNTER, JOB_BRIGAND }
    },

    {
        "Adventurer",
        coord_def(0, 7),
        15,
        { JOB_ARTIFICER, JOB_SHAPESHIFTER, JOB_WANDERER, JOB_DELVER }
    },

    {
        "Zealot",
        coord_def(15, 0),
        20,
        { JOB_BERSERKER, JOB_CINDER_ACOLYTE, JOB_CHAOS_KNIGHT }
    },

    {
        "Warrior-mage",
        coord_def(35, 0),
        21,
        { JOB_WARPER, JOB_HEXSLINGER, JOB_ENCHANTER, JOB_REAVER }
    },

    {
        "Mage",
        coord_def(56, 0),
        22,
        { JOB_HEDGE_WIZARD, JOB_CONJURER, JOB_SUMMONER, JOB_FORGEWRIGHT, JOB_NECROMANCER, JOB_FIRE_ELEMENTALIST, JOB_ICE_ELEMENTALIST, JOB_AIR_ELEMENTALIST, JOB_EARTH_ELEMENTALIST, JOB_ALCHEMIST }
    },
};
